apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-debian
spec:
  serviceName: my-debian
  replicas: 1
  selector:
    matchLabels:
      app: my-debian
  template:
    metadata:
      labels:
        app: my-debian
    spec:
      containers:
      - name: my-debian-container
        image: debian:stable-slim
        command: [ "sleep", "infinity" ]
        volumeMounts:
        - name: data
          mountPath: /mydata
  volumeClaimTemplates:		
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: rancher-local
      resources:
        requests:
          storage: 200Mi
